In [2]:
import numpy as np
from sklearn import datasets


In [6]:
digit = datasets.load_digits()

In [7]:
X = digit.data
y = digit.target

In [9]:
X.shape

y.shape

X.dtype

y.dtype

dtype('int32')

In [10]:
X.shape

(1797, 64)

In [11]:
y.shape

(1797,)

In [12]:
y.dtype

dtype('int32')

In [58]:
X[1].shape

(64,)

In [14]:
X[1].reshape(8,8)

array([[ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.],
       [ 0.,  0.,  0., 11., 16.,  9.,  0.,  0.],
       [ 0.,  0.,  3., 15., 16.,  6.,  0.,  0.],
       [ 0.,  7., 15., 16., 16.,  2.,  0.,  0.],
       [ 0.,  0.,  1., 16., 16.,  3.,  0.,  0.],
       [ 0.,  0.,  1., 16., 16.,  6.,  0.,  0.],
       [ 0.,  0.,  1., 16., 16.,  6.,  0.,  0.],
       [ 0.,  0.,  0., 11., 16., 10.,  0.,  0.]])

In [15]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state=19)

In [16]:
X_train.shape


(1437, 64)

In [17]:
X_test.shape

(360, 64)

In [19]:
y_train.shape

(1437,)

In [20]:
y_test.shape

(360,)

In [25]:
from sklearn.preprocessing import StandardScaler
stardard =  StandardScaler()
stardard.fit(X_train) # 算出 X_train 的 均值 和 方差 

X_train_transform = stardard.transform(X_train) # 
X_test_transform = stardard.transform(X_test)

print(X_train_transform.shape)
print(X_test_transform.shape)
print(X_train_transform.dtype)
print(X_test_transform.dtype)

(1437, 64)
(360, 64)
float64
float64


In [31]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)

knn_clf.fit(X_train_transform,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [32]:
score = knn_clf.score(X_test_transform,y_test)
score

0.9805555555555555

In [33]:
y_prediction = knn_clf.predict(X_test_transform)
y_prediction

array([7, 4, 7, 0, 5, 5, 3, 5, 7, 2, 4, 8, 8, 0, 3, 0, 2, 8, 2, 3, 0, 9,
       1, 1, 7, 4, 1, 1, 7, 5, 4, 6, 2, 7, 5, 9, 0, 3, 7, 6, 9, 6, 1, 3,
       2, 4, 0, 8, 9, 4, 1, 7, 3, 9, 7, 5, 4, 2, 7, 9, 3, 4, 6, 7, 7, 8,
       4, 8, 1, 5, 7, 8, 3, 6, 9, 8, 3, 5, 4, 2, 9, 8, 9, 3, 8, 5, 6, 2,
       2, 4, 1, 1, 5, 5, 3, 8, 2, 5, 3, 0, 3, 5, 3, 9, 1, 0, 2, 4, 3, 8,
       4, 4, 9, 6, 1, 1, 8, 0, 6, 5, 8, 5, 1, 1, 6, 1, 0, 4, 3, 2, 8, 3,
       9, 3, 7, 2, 8, 7, 7, 4, 0, 1, 5, 0, 6, 0, 2, 4, 2, 6, 3, 1, 3, 0,
       2, 9, 9, 9, 7, 1, 8, 4, 1, 4, 5, 9, 1, 0, 6, 4, 1, 8, 3, 4, 0, 3,
       0, 9, 1, 5, 6, 0, 5, 2, 8, 9, 5, 2, 7, 4, 2, 7, 6, 9, 2, 8, 6, 6,
       5, 4, 6, 7, 0, 5, 9, 3, 9, 2, 7, 6, 8, 9, 0, 6, 7, 2, 6, 1, 4, 1,
       7, 1, 2, 0, 5, 0, 3, 0, 2, 2, 7, 4, 6, 8, 6, 6, 5, 8, 9, 5, 7, 6,
       7, 0, 5, 1, 3, 7, 2, 7, 9, 8, 3, 7, 3, 2, 9, 1, 1, 1, 4, 2, 2, 7,
       3, 9, 7, 8, 6, 0, 8, 3, 3, 9, 9, 1, 5, 0, 6, 6, 6, 5, 8, 7, 7, 4,
       6, 1, 8, 5, 3, 1, 2, 4, 7, 4, 9, 9, 5, 6, 6,

In [34]:
y_test

array([7, 4, 7, 0, 5, 5, 3, 5, 7, 2, 4, 8, 8, 0, 3, 0, 2, 8, 2, 3, 0, 9,
       1, 1, 7, 4, 8, 8, 7, 5, 4, 6, 2, 7, 5, 9, 0, 3, 7, 6, 9, 6, 1, 3,
       2, 4, 0, 8, 9, 4, 1, 7, 3, 9, 7, 5, 4, 2, 7, 9, 3, 4, 6, 7, 7, 8,
       4, 8, 1, 5, 7, 8, 3, 6, 9, 8, 3, 5, 4, 2, 9, 8, 9, 3, 8, 5, 6, 2,
       2, 4, 1, 1, 5, 5, 3, 8, 2, 5, 3, 0, 3, 5, 3, 9, 1, 0, 2, 4, 3, 8,
       4, 4, 9, 6, 1, 1, 8, 0, 6, 5, 8, 5, 1, 1, 6, 1, 0, 4, 3, 2, 8, 3,
       9, 3, 7, 2, 8, 7, 7, 4, 0, 1, 5, 0, 6, 0, 2, 4, 2, 6, 3, 1, 3, 0,
       2, 9, 9, 9, 7, 1, 8, 4, 1, 4, 5, 9, 1, 0, 6, 4, 1, 8, 3, 4, 0, 3,
       0, 9, 1, 5, 6, 0, 9, 2, 8, 9, 5, 2, 7, 4, 2, 7, 6, 9, 3, 8, 6, 6,
       5, 4, 6, 7, 0, 5, 9, 3, 9, 2, 7, 6, 8, 9, 0, 6, 7, 2, 6, 1, 4, 1,
       7, 1, 2, 0, 5, 0, 3, 0, 2, 2, 7, 4, 6, 8, 6, 6, 5, 8, 9, 5, 7, 6,
       7, 0, 5, 1, 3, 7, 2, 7, 9, 8, 3, 7, 3, 2, 9, 1, 1, 1, 4, 2, 2, 7,
       3, 9, 7, 8, 6, 0, 8, 3, 3, 9, 9, 1, 5, 0, 6, 6, 9, 5, 8, 7, 7, 4,
       6, 1, 8, 5, 3, 1, 2, 4, 7, 4, 9, 9, 5, 6, 6,

In [43]:
def find_best_K(K_range):
    best_score = 0
    for i in range(1,K_range):
        knn_clf = KNeighborsClassifier(n_neighbors=i)
        knn_clf.fit(X_train_transform,y_train)
        score = knn_clf.score(X_test_transform,y_test)
        if score > best_score:
            best_score = score
            best_k = i;
    return best_k,best_score       
        

In [44]:
best_k,best_score = find_best_K(10)

In [45]:
print(best_k)
print(best_score)

3
0.9805555555555555


In [59]:
def find_best_K_method(K_range):
    best_score = 0.0
    for d in ['uniform','distance']:
        for i in range(1,K_range):
            knn_clf = KNeighborsClassifier(n_neighbors=i,weights=d)
            knn_clf.fit(X_train_transform,y_train)
            score = knn_clf.score(X_test_transform,y_test)
            if score > best_score:
                best_score = score
                best_method = d
                best_K = i
    return best_K,best_score,best_method

In [60]:
best_K,best_score,best_method = find_best_K_method(10)
print(best_K)
print(best_score)
print(best_method)

4
0.9833333333333333
distance


In [61]:
def find_best_K_method_p(K_range,ps):
    distance_method = "" 
    best_score = 0.0
    best_p = 0
    for p in range(1,ps):
        for d in ['uniform','distance']:
            for i in range(1,K_range):
                knn_clf = KNeighborsClassifier(n_neighbors=i,weights=d,p = p)
                knn_clf.fit(X_train_transform,y_train)
                score = knn_clf.score(X_test_transform,y_test)
                if score > best_score:
                    best_score = score
                    best_method = d
                    best_K = i
                    best_p = p
    return best_K,best_score,best_method,best_p 

In [65]:
best_K,best_score,best_method,best_p = find_best_K_method_p(10,4)
print(best_K)
print(best_score)
print(best_method)
print(best_p)

4
0.9833333333333333
distance
2
